### ISSUE TITLE
Query parser

### ISSUE THREAD

**Issue by MrJasperge** [MartLugt/PWS#13]
na joke te hebben uitgevoerd

`
('joke', 1.0)
Traceback (most recent call last):
  File "assistant.py", line 59, in <module>
    detect()
  File "assistant.py", line 55, in detect
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 47, in callback
    main()
  File "assistant.py", line 36, in main
    intent = query_parser.parse(text.lower())
AttributeError: 'bool' object has no attribute 'lower'
`

**Comment by MrJasperge** [comment]
Dit gebeurt alleen na er voorafgaand iets niet werd verstaan, e.g.:
Jarvis
_ding_
vvww
_dong_
_Sorry, I couldn't quite catch that_
Joke
**_joke is executed_**
error

**Comment by MrJasperge** [comment]
Dit gebeurt altijd nadat jarvis iets niet heeft verstaan, niet alleen bij joke dus

**Comment by MartLugt** [comment]
probably fixed in ecc28fb787aa90986bc7b37dddb2683b64c5e018

**Comment by MartLugt** [comment]
duplicate of #9
