### ISSUE TITLE
STT too quickly aborted

### ISSUE THREAD

**Issue by MrJasperge** [MartLugt/PWS#7]
Jarvis
What's the weather
`Listening...
First be silent, calibrating silence
We are now recording. Start talking for it to start.
First be silent, calibrating silence
We are now recording. Start talking for it to start.
First be silent, calibrating silence
We are now recording. Start talking for it to start.
First be silent, calibrating silence
We are now recording. Start talking for it to start.
First be silent, calibrating silence
We are now recording. Start talking for it to start.
INFO:snowboy:Keyword 1 detected at time: 2018-02-20 17:42:48
Recording Activated
Recording is done
what's the`

stopped recording before I was done talking

**Comment by MrJasperge** [comment]
This time it didn't hear me at all and it started recording a second time when I said 'what's the weather' louder

`First be silent, calibrating silence
We are now recording. Start talking for it to start.
INFO:snowboy:Keyword 1 detected at time: 2018-02-20 17:43:06
Recording Activated
Recording is done
[]
Recording Activated
Recording is done
weather`

**Comment by MartLugt** [comment]
prob fixed
